const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const dir=__dirname,read=n=>fs.readFileSync(path.join(dir,n),'utf8');
const refs=JSON.parse(read('references.json'));
const files=['organic','technical','mythic','draconic','orbital'].map(n=>`motion-${n}-art.js`);
const data='const motionThemes=[];\n'+files.map(read).join('\n')+'\n'+`motionThemes.forEach(t=>t.name=${JSON.stringify(Object.fromEntries(refs.map(r=>[r.id,r.name])))}[t.id]||t.name);`;
const engine=read('motion-engine.js'),ctx={};vm.createContext(ctx);vm.runInContext(data+'\n'+engine,ctx);
const themes=vm.runInContext('motionThemes',ctx),kit=ctx.IconflowMotion;
console.log(JSON.stringify(kit.validate(themes)));
const old=read('motion-shell-base.html'),labels={back:'Back',reload:'Reload',download:'Download',bookmark:'Bookmark',history:'History',library:'Library'};
let cropId=0;
function crop(r,box,w,h,exclude=[]){const id=++cropId;return `<svg class="reference-art" width="${w}" height="${h}" viewBox="${box.join(' ')}" aria-hidden="true"><defs><clipPath id="original-${id}"><rect x="${box[0]}" y="${box[1]}" width="${box[2]}" height="${box[3]}"/></clipPath>${exclude.length?`<mask id="exclude-${id}" maskUnits="userSpaceOnUse" x="0" y="0" width="1536" height="1024"><rect width="1536" height="1024" fill="white"/>${exclude.map(b=>`<rect x="${b[0]}" y="${b[1]}" width="${b[2]}" height="${b[3]}" fill="black"/>`).join('')}</mask>`:''}</defs><g clip-path="url(#original-${id})"><use href="#source-${r.sheet}"${exclude.length?` mask="url(#exclude-${id})"`:''}/></g></svg>`;}
function reference(r){if(!r.toolbar)return '<p class="original">New orbital study · hover and click to compare the motion stages.</p>';return `<details class="original"><summary>Original sheet · compare outlines</summary><div class="original-toolbar">${Object.keys(labels).map(k=>`<div>${crop(r,r.toolbar[k],42,42,r.toolbarExclusions?.[k])}<span>${labels[k]}</span></div>`).join('')}</div><div class="original-poses">${['rest','hover','click'].map(k=>`<div>${crop(r,r.states[k],115,105)}<span>${k}</span></div>`).join('')}</div></details>`;}
function card(t,i){const r=refs.find(r=>r.id===t.id)||{name:t.name,family:"Orbital"};return `<section class="theme" data-theme="${t.id}" data-family="${kit.esc(r.family)}" aria-labelledby="heading-${t.id}"><div class="card-head"><div class="identity"><span class="number">${String(i+1).padStart(2,'0')}</span><div><h2 id="heading-${t.id}">${kit.esc(r.name)}</h2><p class="family">${kit.esc(r.family)}</p></div></div><button class="replay" type="button" aria-label="Replay ${kit.esc(r.name)} motions">Replay clicks</button></div><p class="description">${kit.esc(t.note||'Connected outlines; independent part motion.')}</p><div class="buttons">${Object.keys(labels).map(k=>`<button class="sample" type="button" data-key="${k}" aria-label="${kit.esc(r.name)}: ${labels[k]}" ${k==='bookmark'?'aria-pressed="false" data-saved="false"':''}><span class="stage">${kit.svg(t,k,64)}</span><span class="small-sizes">${kit.svg(t,k,16)}${kit.svg(t,k,18)}</span><span class="sample-label">${labels[k]}</span></button>`).join('')}</div><div class="inspect-row"><label>Inspect <select class="inspect" aria-label="Inspect ${kit.esc(r.name)} action">${Object.keys(labels).map(k=>`<option value="${k}" ${k==='reload'?'selected':''}>${labels[k]}</option>`).join('')}</select></label><span>Click any toolbar button to inspect its motion.</span></div><div class="reference-panel"><div class="reference-demo"><span class="reference-label">LIVE · RELOAD</span><button class="pose-live" type="button" aria-label="${kit.esc(r.name)}: animate reload"><span class="stage">${kit.svg(t,'reload',154,0)}</span></button><span class="pose-hint">Hover · press · click</span></div><div class="pose-choices">${['Rest','Hover','Click'].map((n,j)=>`<button class="pose-choice" type="button" data-pose="${j}" aria-pressed="false" aria-label="Pin ${kit.esc(r.name)} ${n.toLowerCase()} pose">${kit.svg(t,'reload',88,j)}<span>${n}</span></button>`).join('')}</div></div><div class="motion-story"><span class="story-label">CLICK SEQUENCE · 4 SAMPLED FRAMES</span><div class="motion-strip">${kit.storyboard(t,'reload',84)}</div></div><div class="motion-notes"><div><b>PARTS</b><span class="part-count">${t.icons.reload.length} reload parts · hover + click choreography</span></div><div><b>TRANSITIONS</b>Velocity retained on interruption · 0 idle loops</div></div>${reference(r)}</section>`;}
let html=old.replace(/<title>.*?<\/title>/,'<title>Iconflow — continuous line-art motion</title>');
html=html.replace(/<div class="gallery" id="gallery">[\s\S]*?<\/div>\s*<footer>/,`<div class="gallery" id="gallery">${themes.map(card).join('\n')}</div>\n<footer>`);
html=html.replace(/<label class="control">Artwork[\s\S]*?<\/label>\n/,'');
html=html.replace('ICONFLOW / EXACT SHEET ARTWORK / 01—21','ICONFLOW / CONTINUOUS LINE MOTION / 01—23');
html=html.replace('<h1>From the sheets.</h1>','<h1>Lines in motion.</h1>');
html=html.replace(/<p class="intro">[\s\S]*?<\/p>/,'<p class="intro">23 monochrome themes: 21 refined originals and 2 new orbital sets with counter-moving stars and unequal orbital speeds. Reload mechanisms wind, assemble, exchange, and re-seat material along their paths. Hover and click have separate multipart sequences. Orbits and coils cross in front of and behind their anchors; wings, ribbons, leaves, and panels keep their connected joints. Hover, press, or click. Click any toolbar button for an enlarged preview. Inspect Rest / Hover / Click for all 6 actions.</p>');
html=html.replace(/<footer>[\s\S]*?<\/footer>/,'<footer><div class="footer-row"><p>21 interpretations of the approved line art and 2 new orbital studies. Open “Original sheet” inside each card to compare the source pixels. Winding bands, segmented irises, rosettes, coils, and orbital exchanges give each reload a separate mechanism. Toolbar and inspector use the same geometry.</p><p>23 themes · 138 toolbar glyphs · 23 action inspectors</p></div><p>Tab / Enter / Space supported. Reduced-motion setting respected. Disabled and busy controls pause their motion. No network requests or idle animation loops.</p><p>Path topology, connected joints, frame timing, and input events checked offline. Live browser rendering and Zen integration remain untested.</p><details class="motion-sources"><summary>Motion study references</summary><p><a href="https://tips.clip-studio.com/en-us/articles/954" target="_blank" rel="noopener noreferrer">CELSYS: key poses and follow-through</a> · <a href="https://blog.animschool.edu/2024/07/19/acting-through-anticipation/" target="_blank" rel="noopener noreferrer">AnimSchool: anticipation</a> · <a href="https://archive2.news.brown.edu/2007-2015/articles/2012/04/foldflap.html" target="_blank" rel="noopener noreferrer">Brown: bat wing folding</a> · <a href="https://vimeo.com/410611055" target="_blank" rel="noopener noreferrer">Olivier Staphylas: dragon animation development</a> · <a href="https://www.vam.ac.uk/articles/turning-the-pages-of-an-illuminated-manuscript/" target="_blank" rel="noopener noreferrer">V&amp;A: manuscript page turns</a> · <a href="https://www.physics.wisc.edu/ingersollmuseum/exhibits/opticscolor/kaleidoscope/" target="_blank" rel="noopener noreferrer">UW–Madison: kaleidoscope symmetry</a> · <a href="https://svs.gsfc.nasa.gov/4642/" target="_blank" rel="noopener noreferrer">NASA SVS: orbital planes</a> · <a href="https://www.eso.org/~ohainaut/astrolabe/manual.html" target="_blank" rel="noopener noreferrer">Olivier Hainaut: astrolabe mechanisms</a></p></details></footer>');
html=html.replace('</style>',`.motion-story{border-top:1px solid var(--line);padding:13px 16px 9px}.story-label{font:9px ui-monospace,monospace;letter-spacing:.08em;color:var(--muted)}.motion-strip{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:4px;margin-top:8px}.motion-strip figure{margin:0;min-width:0;text-align:center}.motion-strip .motion-art{max-width:100%;width:100%;height:82px}.motion-strip figcaption{font:10px ui-monospace,monospace;color:var(--muted);margin-top:4px}.motion-sources{margin-top:14px}.motion-sources summary{cursor:pointer}.motion-sources a{color:inherit;text-underline-offset:3px}.inspect-row{display:flex;gap:12px;align-items:center;justify-content:space-between;padding:10px 18px;border-top:1px solid var(--line);font-size:11px;color:var(--muted)}.inspect-row label{display:flex;align-items:center;gap:8px}.inspect{color:var(--ink);background:var(--ui);border:1px solid var(--line);border-radius:4px;padding:5px 8px;font:inherit}.sample .stage{height:74px;width:100%}.sample .stage>.motion-art{width:min(100%,64px);height:auto;aspect-ratio:1}.motion-art{stroke:currentColor;fill:none;overflow:visible}.motion-art .motion-root{transform-box:view-box}.sample.is-pressed .stage,.pose-live.is-pressed .stage{transform:none}.stage{transition:none}.reference-demo .pose-live{height:151px}.pose-live .stage{height:136px}.pose-live .stage>.motion-art{width:100%;height:136px}.pose-choice .motion-art{height:112px;width:100%}.original{border-top:1px solid var(--line);padding:10px 18px 14px}.original summary{cursor:pointer;font-size:11px;color:var(--muted)}.original-toolbar{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin-top:15px}.original-toolbar>div,.original-poses>div{display:flex;align-items:center;flex-direction:column;gap:5px}.original-toolbar span,.original-poses span{font-size:10px;color:var(--muted)}.original-poses{display:grid;grid-template-columns:repeat(3,1fr);margin-top:17px;gap:12px}.original-poses svg{max-width:100%}.reference-art{fill:none;stroke:none}.theme:has(.original[open]) .original summary{color:var(--ink)}.sample[data-busy=true]::before{content:'BUSY';position:absolute;top:0;font:9px ui-monospace,monospace}.pose-choice[aria-pressed=true]{background:var(--well)}@media(prefers-reduced-motion:reduce){.stage{transition:none}}\n</style>`);
html=html.replace('aria-label="21 themes, 126 buttons, no idle loops"','aria-label="23 themes, 138 buttons, no idle loops"').replace('<strong>21</strong>themes','<strong>23</strong>themes').replace('<strong>126</strong>buttons','<strong>138</strong>buttons');
html=html.replace('All 21 themes','All 23 themes').replace('<option>Draconic</option>','<option>Draconic</option><option>Orbital</option>');
html=html.replace('48 px art · 16 / 18 px toolbar','64 px art · 16 / 18 px toolbar');
html=html.replace('Hover or click a toolbar glyph. Compare the 3 bookmark poses beneath each set.','Hover or click any button. Inspect all 6 actions beneath each set.');
html=html.replace('</body>',`<script>\n${data}\n${engine}\n</script>\n</body>`);
fs.writeFileSync(path.join(dir,'Iconflow-Theme-Explorer.html'),html);
console.log(`Built ${Buffer.byteLength(html)} bytes; 23 static cards; exact source comparisons embedded.`);
