// ponytail: 23 themes / 6 toolbar actions; no idle renderer or animation dependency.
const MotionKit = (() => {
  const numberRE = /[-+]?(?:\d*\.\d+|\d+\.?\d*)(?:e[-+]?\d+)?/ig;
  const identity = [0,0,0,1,1];
  const maskPrefix=`iconflow-mask-${typeof document==='undefined'?'static':Math.random().toString(36).slice(2)}`;let maskCount=0;
  const fmt = n => String(Math.round(n*10000)/10000);
  const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function parse(d) { return {chunks:d.split(numberRE), values:(d.match(numberRE)||[]).map(Number), signature:d.replace(numberRE,'#').replace(/[\s,]+/g,'')}; }
  // ponytail: 64 arclength samples/cubic; refine when guide error exceeds .01 SVG units.
  const trackCache=new Map(),tau=Math.PI*2;
  function compileTrack(track){const key=JSON.stringify(track);if(trackCache.has(key))return trackCache.get(key);let result;
    if(track&&typeof track==='object'){const e=track.ellipse;if(!Array.isArray(e)||e.length!==5||!e.every(Number.isFinite)||e[2]<=0||e[3]<=0||!Number.isFinite(track.pitch??0))throw Error('Flow ellipse requires cx cy rx ry rotation and finite pitch');const [cx,cy,rx,ry,r]=e,c=Math.cos(r*Math.PI/180),s=Math.sin(r*Math.PI/180);result={depth:true,pitch:track.pitch||0,sample(u){const a=u*tau,ca=Math.cos(a),sa=Math.sin(a);return {x:cx+c*rx*ca-s*ry*sa,y:cy+s*rx*ca+c*ry*sa,dx:tau*(-c*rx*sa-s*ry*ca),dy:tau*(-s*rx*sa+c*ry*ca),depth:sa};}};
    }else{if(typeof track!=='string'||!/^[\s\d.,+eE\-MLQCZ]+$/.test(track)||!track.trim().endsWith('Z'))throw Error('Flow track requires one closed uppercase M/L/Q/C/Z contour');const commands=track.match(/[MLQCZ][^MLQCZ]*/g)||[],segments=[];let p,start;
      const cubic=(v,t)=>{const z=1-t;return {x:z*z*z*v[0]+3*z*z*t*v[2]+3*z*t*t*v[4]+t*t*t*v[6],y:z*z*z*v[1]+3*z*z*t*v[3]+3*z*t*t*v[5]+t*t*t*v[7],dx:3*z*z*(v[2]-v[0])+6*z*t*(v[4]-v[2])+3*t*t*(v[6]-v[4]),dy:3*z*z*(v[3]-v[1])+6*z*t*(v[5]-v[3])+3*t*t*(v[7]-v[5])};};
      for(const command of commands){const op=command[0],v=(command.slice(1).match(numberRE)||[]).map(Number);if(v.some(n=>!Number.isFinite(n)))throw Error('Nonfinite flow guide');if(op==='M'){if(start||v.length!==2)throw Error('Flow guide needs one move');p=v;start=v;continue;}if(!p)throw Error('Flow guide must start with M');let end,controls;if(op==='Z'){if(v.length)throw Error('Invalid flow close');end=start;controls=[p[0]+(end[0]-p[0])/3,p[1]+(end[1]-p[1])/3,p[0]+(end[0]-p[0])*2/3,p[1]+(end[1]-p[1])*2/3];}else if(op==='L'&&v.length===2){end=v;controls=[p[0]+(v[0]-p[0])/3,p[1]+(v[1]-p[1])/3,p[0]+(v[0]-p[0])*2/3,p[1]+(v[1]-p[1])*2/3];}else if(op==='Q'&&v.length===4){end=v.slice(2);controls=[p[0]+(v[0]-p[0])*2/3,p[1]+(v[1]-p[1])*2/3,end[0]+(v[0]-end[0])*2/3,end[1]+(v[1]-end[1])*2/3];}else if(op==='C'&&v.length===6){end=v.slice(4);controls=v.slice(0,4);}else throw Error('Invalid flow guide command');if(Math.hypot(end[0]-p[0],end[1]-p[1])>1e-10||controls.some((n,i)=>Math.abs(n-p[i%2])>1e-10))segments.push([...p,...controls,...end]);p=end;}
      const lut=[];let length=0;for(const [index,v]of segments.entries()){let prev=cubic(v,0);for(let j=1;j<=64;j++){const q=cubic(v,j/64),distance=Math.hypot(q.x-prev.x,q.y-prev.y);if(distance>1e-12){lut.push({from:length,to:length+distance,index,t0:(j-1)/64,t1:j/64});length+=distance;}prev=q;}}if(!length)throw Error('Flow guide has no length');result={depth:false,pitch:0,sample(u){const distance=((u%1+1)%1)*length;let lo=0,hi=lut.length-1;while(lo<hi){const mid=(lo+hi)>>1;if(lut[mid].to<distance)lo=mid+1;else hi=mid;}const b=lut[lo],t=b.t0+(b.t1-b.t0)*(distance-b.from)/(b.to-b.from),q=cubic(segments[b.index],t),norm=Math.hypot(q.dx,q.dy)||1;return {...q,dx:q.dx/norm*length,dy:q.dy/norm*length,depth:0};}};
    }if(trackCache.size>=128)trackCache.clear();trackCache.set(key,result);return result;
  }
  function model(part) {
    const paths=[part.d,part.h||part.d,part.c||part.d].map(parse);
    if(!paths.every(p=>p.signature===paths[0].signature))throw Error('Morph signature differs: '+part.d);
    if(/[Aa]/.test(part.d))throw Error('Use cubic curves for morphing; arc flags are discrete');
    if(part.t&&(!Array.isArray(part.t)||part.t.length!==3||part.t.some(t=>t.length!==5||!t.every(Number.isFinite))))throw Error('Expected 3 transforms of 5 finite values');
    if(part.o&&(part.o.length!==2||!part.o.every(Number.isFinite)))throw Error('Expected a finite two-coordinate origin');
    if(part.rate!==undefined&&(!Number.isFinite(part.rate)||part.rate<=0))throw Error('Rate must be positive');
    if(part.turn!==undefined&&!Number.isFinite(part.turn)||part.hoverTurn!==undefined&&(!Number.isFinite(part.hoverTurn)||part.hoverTurn<0||part.hoverTurn>1))throw Error('Turn and hover fraction must be finite');
    for(const key of ['opacity','draw'])if(part[key]!==undefined&&(!Array.isArray(part[key])||part[key].length!==3||!part[key].every(v=>Number.isFinite(v)&&v>=0&&v<=1)))throw Error(`${key} requires 3 finite values from 0 to 1`);
    if(part.maskOnly!==undefined&&typeof part.maskOnly!=='boolean')throw Error('maskOnly must be boolean');
    let flowTrack;if(part.flow){const f=part.flow;if(!['head','trail'].includes(f.mode)||![f.start??0,f.heading??0,f.width??0,f.taper??1,f.scaleByDepth??0,f.cycles??1].every(Number.isFinite)||(f.width??0)<0||(f.taper??1)<0||(f.taper??1)>1||(f.scaleByDepth??0)<0||(f.scaleByDepth??0)>.35||f.anchor&&(!Array.isArray(f.anchor)||f.anchor.length!==2||!f.anchor.every(Number.isFinite))||f.span&&(!Array.isArray(f.span)||f.span.length!==3||!f.span.every(v=>Number.isFinite(v)&&v>=0&&v<=3))||f.layer&&!['front','back'].includes(f.layer))throw Error('Invalid flow configuration');flowTrack=compileTrack(f.track);if(f.layer&&!flowTrack.depth)throw Error('Flow layers require an ellipse depth track');}
    const hasPhase=!!part.flow&&(part.flow.phase!==undefined||part.flow.wrap===true);
    if(part.flow&&(part.flow.wrap!==undefined&&typeof part.flow.wrap!=='boolean'||part.flow.direction!==undefined&&![1,-1].includes(part.flow.direction)||part.flow.phase!==undefined&&(!Array.isArray(part.flow.phase)||part.flow.phase.length!==3||!part.flow.phase.every(Number.isFinite))))throw Error('Invalid authored flow phase, wrap, or direction');
    const m={part,chunks:paths[0].chunks,n:paths[0].values.length,states:paths.map((p,i)=>[...p.values,...(part.t?.[i]||identity),part.opacity?.[i]??1,part.draw?.[i]??1,...(part.flow?[part.flow.span?.[i]??1]:[]),...(hasPhase?[part.flow.phase?.[i]??0]:[])]),origin:part.o||[12,12],flowTrack,hasPhase};
    m.poses=Object.fromEntries(['rest','hover','click'].map((name,i)=>[name,m.states[i]]));
    for(const [name,pose]of Object.entries(part.poses||{})){
      if(Object.hasOwn(m.poses,name)||!pose||![0,1,2].includes(pose.base??0))throw Error('Invalid named pose: '+name);
      const a=m.states[pose.base??0].slice();
      if(pose.d!==undefined){const p=parse(pose.d);if(p.signature!==paths[0].signature||!p.values.every(Number.isFinite))throw Error('Named pose topology differs: '+name);a.splice(0,m.n,...p.values);}
      if(pose.t!==undefined){if(!Array.isArray(pose.t)||pose.t.length!==5||!pose.t.every(Number.isFinite))throw Error('Named pose transform invalid: '+name);a.splice(m.n,5,...pose.t);}
      for(const [key,offset,max]of [['opacity',5,1],['draw',6,1],['span',7,3]])if(pose[key]!==undefined){if(!Number.isFinite(pose[key])||pose[key]<0||pose[key]>max||key==='span'&&!part.flow)throw Error('Named pose channel invalid: '+name);a[m.n+offset]=pose[key];}
      if(pose.phase!==undefined){if(!hasPhase||!Number.isFinite(pose.phase))throw Error('Named phase requires authored flow phase channel: '+name);a[m.n+8]=pose.phase;}
      m.poses[name]=a;
    }
    for(const [event,beats]of Object.entries(part.beats||{}))if(!['hover','click','leave'].includes(event)||!Array.isArray(beats)||!beats.length||beats.length>8||beats.some((b,i)=>!Array.isArray(b)||b.length!==2||!Number.isFinite(b[0])||b[0]<0||b[0]>1800||(i?b[0]<=beats[i-1][0]:b[0]!==0)||!Object.hasOwn(m.poses,b[1])))throw Error('Invalid finite beats: '+event);
    return m;
  }
  function flowSample(m,a,u=0){const f=m.part.flow,direction=f.direction||1,span=Math.max(0,Math.min(3,a[m.n+7])),phase=(f.start||0)+(a[m.n+2]-m.states[0][m.n+2])/(m.part.turn||360)*(f.cycles??1)+(m.hasPhase?a[m.n+8]:0)+(f.wrap?span*direction:0),q=m.flowTrack.sample(phase+u*direction),dx=q.dx*direction,dy=q.dy*direction-m.flowTrack.pitch,norm=Math.hypot(dx,dy)||1;return {x:q.x,y:q.y-m.flowTrack.pitch*u,tx:dx/norm,ty:dy/norm,depth:q.depth,scale:1+(f.scaleByDepth||0)*q.depth,phase};}
  function trailPath(m,a,mask=false){const f=m.part.flow,span=Math.max(0,Math.min(3,a[m.n+7])),phase=flowSample(m,a).phase;if(span<1e-7)return 'M0 0';const cuts=[-span,0];if(f.layer){const direction=f.direction||1,end=phase-span*direction;for(let k=Math.ceil(Math.min(end,phase)*2);k<=Math.floor(Math.max(end,phase)*2);k++){const u=(k/2-phase)/direction;if(u>-span+1e-9&&u<-1e-9)cuts.push(u);}}cuts.sort((x,y)=>x-y);const smooth=points=>{let out=`M${fmt(points[0][0])} ${fmt(points[0][1])}`;for(let i=0;i<points.length-1;i++){const p0=points[Math.max(0,i-1)],p=points[i],q=points[i+1],q1=points[Math.min(points.length-1,i+2)];out+=` C${fmt(p[0]+(q[0]-p0[0])/6)} ${fmt(p[1]+(q[1]-p0[1])/6)} ${fmt(q[0]-(q1[0]-p[0])/6)} ${fmt(q[1]-(q1[1]-p[1])/6)} ${fmt(q[0])} ${fmt(q[1])}`;}return out;};let out='';
    for(let i=0;i<cuts.length-1;i++){const from=cuts[i],to=cuts[i+1],depth=flowSample(m,a,(from+to)/2).depth;if(f.layer&&(f.layer==='front'?depth<0:depth>=0))continue;const count=Math.max(4,Math.ceil((to-from)*64)),left=[],right=[];for(let j=0;j<=count;j++){const u=from+(to-from)*j/count,q=flowSample(m,a,u),w=(f.width||0)*q.scale*((f.taper??1)+(1-(f.taper??1))*(u+span)/span)/2;left.push([q.x-q.ty*w,q.y+q.tx*w]);right.push([q.x+q.ty*w,q.y-q.tx*w]);}out+=smooth(left);if(f.width){right.reverse();out+=` ${mask||Math.abs(to)<1e-9?'L':'M'}${fmt(right[0][0])} ${fmt(right[0][1])}`+smooth(right).replace(/^M[^C]+/,'');if(mask)out+=' Z';else if(Math.abs(from+span)<1e-9)out+=` L${fmt(left[0][0])} ${fmt(left[0][1])}`;}}
    return out||'M0 0';
  }
  function path(m,a,mask=false) {if(m.part.flow?.mode==='trail')return trailPath(m,a,mask);return m.chunks.map((s,i)=>s+(i<m.n?fmt(a[i]):'')).join(''); }
  function transform(m,a) { const [x,y,r,sx,sy]=a.slice(m.n),[ox,oy]=m.origin;if(m.part.flow?.mode==='head'){const q=flowSample(m,a),f=m.part.flow,[ax,ay]=f.anchor||m.origin,angle=Math.atan2(q.ty,q.tx)-(f.heading||0)*Math.PI/180,c=Math.cos(angle)*q.scale,s=Math.sin(angle)*q.scale,dx=x+ox-sx*ox-ax,dy=y+oy-sy*oy-ay;return `matrix(${fmt(c*sx)} ${fmt(s*sx)} ${fmt(-s*sy)} ${fmt(c*sy)} ${fmt(q.x+c*dx-s*dy)} ${fmt(q.y+s*dx+c*dy)})`;}return `translate(${fmt(x)} ${fmt(y)}) translate(${ox} ${oy}) rotate(${fmt(m.part.flow?m.states[0][m.n+2]:r)}) scale(${fmt(sx)} ${fmt(sy)}) translate(${-ox} ${-oy})`; }
  function appearance(m,a) {let opacity=Math.max(0,Math.min(1,a[m.n+5]??1));const f=m.part.flow;if(f?.mode==='head'&&f.layer){const depth=flowSample(m,a).depth;if(f.layer==='front'?depth<0:depth>=0)opacity=0;}return {opacity,draw:Math.max(0,Math.min(1,a[m.n+6]??1))};}
  function svg(theme,key,size=48,state=0,demo=false,tracks=null) {
    const parts=demo?theme.demo:theme.icons[key],stroke=(theme.stroke||1.05)*(demo ? .72 : 1),box=demo?'-9 -4 42 32':theme.iconViewBoxes?.[key]||'-2 -2 28 28';
    const [bx,by,bw,bh]=box.trim().split(/[\s,]+/).map(Number),defs=[];
    function partSVG(p,i,mask=false){const m=tracks?.[i].m||model(p),a=tracks?tracks[i].x:m.states[state].slice();if(!tracks&&p.turn&&state)a[m.n+2]=m.states[0][m.n+2]+p.turn*(state===1?(p.hoverTurn??.18):1);const style=appearance(m,a);return `<g data-part="${i}"${mask?' data-mask="true"':''} transform="${transform(m,a)}" opacity="${fmt(style.opacity)}"><path d="${path(m,a,mask)}" stroke-width="${stroke*(p.w||1)}" pathLength="1" stroke-dasharray="${style.draw>=1?'none':fmt(style.draw)+' 1'}" visibility="${style.draw>0?'visible':'hidden'}"${mask?' fill="black" stroke="black"':''}/></g>`;}
    const body=parts.map((p,i)=>{if(p.maskOnly)return '';const art=partSVG(p,i);if(!p.occludedBy?.length)return art;const id=`${maskPrefix}-${++maskCount}`;defs.push(`<mask id="${id}" maskUnits="userSpaceOnUse" maskContentUnits="userSpaceOnUse" x="${bx-bw}" y="${by-bh}" width="${bw*3}" height="${bh*3}" style="mask-type:luminance"><rect x="${bx-bw}" y="${by-bh}" width="${bw*3}" height="${bh*3}" fill="white" stroke="none"/>${p.occludedBy.map(j=>partSVG(parts[j],j,true)).join('')}</mask>`);return `<g mask="url(#${id})">${art}</g>`;}).join('');
    return `<svg class="art motion-art" overflow="visible" width="${size}" height="${size}" viewBox="${esc(box)}" fill="none" stroke="currentColor" stroke-width="${stroke}" stroke-linecap="${theme.cap||'round'}" stroke-linejoin="${theme.join||'round'}" aria-hidden="true">${defs.length?'<defs>'+defs.join('')+'</defs>':''}<g class="motion-root">${body}</g></svg>`;
  }
  // Exact critically damped step: position AND velocity survive target changes.
  function step(x,v,target,omega,dt) { const e=Math.exp(-omega*dt),d=x-target,k=v+omega*d;return [target+(d+k*dt)*e,(v-omega*k*dt)*e]; }
  function makeTracks(parts) {return parts.map(p=>{const m=model(p);return {m,x:m.states[0].slice(),v:m.states[0].map(()=>0),target:m.states[0].slice()};});}
  function targets(tracks,state,turns=0) {for(const q of tracks){q.target=q.m.states[state].slice();if(q.m.part.turn)q.target[q.m.n+2]=q.m.states[0][q.m.n+2]+turns*q.m.part.turn;}}
  function applyBeat(tracks,event){const q=tracks[event.index],turn=q.target[q.m.n+2];q.target=q.m.poses[event.pose].slice();if(q.m.part.turn)q.target[q.m.n+2]=turn;}
  // Authored beats change targets only. One finite clock drives every attached part.
  function play(tracks,event,turns=0){const state={leave:0,hover:1,click:2}[event];if(state===undefined)throw Error('Unknown motion event');targets(tracks,state,turns);const events=[];tracks.forEach((q,index)=>{for(const [at,pose]of q.m.part.beats?.[event]||[])events.push({at,index,pose});});events.sort((a,b)=>a.at-b.at||a.index-b.index);const last=events.at(-1)?.at||0,sequence={events,cursor:0,elapsed:0,duration:event==='click'?Math.max(680,last+240):last};while(sequence.cursor<events.length&&events[sequence.cursor].at===0)applyBeat(tracks,events[sequence.cursor++]);return sequence;}
  function advanceSequence(tracks,sequence,dt,speed=1){if(!sequence)return advance(tracks,dt,speed);const end=sequence.elapsed+Math.max(0,dt)*1000/speed;while(sequence.cursor<sequence.events.length&&sequence.events[sequence.cursor].at<=end+1e-8){const event=sequence.events[sequence.cursor++];advance(tracks,Math.max(0,event.at-sequence.elapsed)*speed/1000,speed);sequence.elapsed=event.at;applyBeat(tracks,event);}const moving=advance(tracks,Math.max(0,end-sequence.elapsed)*speed/1000,speed);sequence.elapsed=end;return moving;}
  function turnGoal(tracks,event,previous=0){const q=tracks.find(q=>q.m.part.turn);if(!q)return previous;const current=(q.x[q.m.n+2]-q.m.states[0][q.m.n+2])/q.m.part.turn;
    if(event==='leave')return Math.ceil(previous-1e-7);
    if(event==='click')return Math.max(Math.floor(current+1e-7)+1,Math.ceil(previous-1e-7));
    if(event==='hover'&&previous-current<.015&&Math.abs(previous-Math.round(previous))<1e-7)return previous+(q.m.part.hoverTurn??.18);
    return previous;
  }
  function advance(tracks,dt,speed=1) {let moving=false;for(const q of tracks){for(let i=0;i<q.x.length;i++){const turn=q.m.part.turn&&i===q.m.n+2;let w=(turn?8:16)*(q.m.part.rate||1)/speed;const distance=q.target[i]-q.x[i];if(turn&&Math.abs(distance)>1e-8&&q.v[i]*distance>0)w=Math.max(w,q.v[i]/distance);[q.x[i],q.v[i]]=step(q.x[i],q.v[i],q.target[i],w,dt);if(Math.abs(q.x[i]-q.target[i])>(turn?.02:.0004)||Math.abs(q.v[i])>(turn?.2:.006))moving=true;}}return moving;}
  function settle(tracks) {for(const q of tracks){q.x=q.target.slice();q.v.fill(0);}}
  function storyboard(theme,key,size=84,demo=false){const tracks=makeTracks(demo?theme.demo:theme.icons[key]),sequence=play(tracks,'click',turnGoal(tracks,'click'));let previous=0;return [.16,.38,.63,.87].map(fraction=>{const ms=Math.round(sequence.duration*fraction);advanceSequence(tracks,sequence,(ms-previous)/1000);previous=ms;return `<figure>${svg(theme,key,size,0,demo,tracks)}<figcaption>${ms} ms</figcaption></figure>`;}).join('');}
  function validate(themes) {
    if(themes.length!==23||new Set(themes.map(t=>t.id)).size!==23)throw Error('Expected 23 unique themes');
    let paths=0,coordinates=0;
    for(const t of themes){if(Object.keys(t.icons).length!==6)throw Error(`${t.id}: expected 6 icons`);for(const [key,box]of Object.entries(t.iconViewBoxes||{})){const a=typeof box==='string'?box.trim().split(/[\s,]+/).map(Number):[];if(!t.icons[key]||a.length!==4||!a.every(Number.isFinite)||a[2]<=0||a[3]<=0)throw Error(`${t.id}/${key}: viewBox requires 4 finite numbers and positive width/height`);}for(const parts of [...Object.values(t.icons),t.demo]){if(!parts.length)throw Error(`${t.id}: empty geometry`);for(const [i,p]of parts.entries()){if(p.occludedBy!==undefined&&(!Array.isArray(p.occludedBy)||!p.occludedBy.length||p.occludedBy.some(j=>!Number.isInteger(j)||j<0||j>=parts.length||j===i||!(parts[j].flow?.mode==='trail'&&parts[j].flow.width>0)&&![parts[j].d,parts[j].h||parts[j].d,parts[j].c||parts[j].d].every(d=>d.trim().endsWith('Z')))))throw Error(`${t.id}: occludedBy requires other closed contours in the same icon`);const m=model(p);if(!m.states.flat().every(Number.isFinite))throw Error(`${t.id}: nonfinite coordinate`);paths++;coordinates+=m.n;}}}
    return {themes:themes.length,icons:themes.length*6,demos:themes.length,paths,coordinates};
  }
  return {parse,model,path,transform,appearance,flowSample,svg,storyboard,step,makeTracks,targets,play,advanceSequence,turnGoal,advance,settle,validate,esc};
})();
globalThis.IconflowMotion=MotionKit;
if(typeof document!=='undefined') (()=>{
  const $=id=>document.getElementById(id), gallery=$('gallery'), status=$('status'),motion=$('motion'),speed=$('speed'),saved=$('saved');
  const reduced=matchMedia('(prefers-reduced-motion: reduce)'),items=[],active=new Set();
  let frame=0,last=0,pausedAt=0;
  const allowed=()=>motion.checked&&!reduced.matches;
  function paint(item){for(const q of item.tracks){const d=MotionKit.path(q.m,q.x),transform=MotionKit.transform(q.m,q.x),style=MotionKit.appearance(q.m,q.x);for(const node of q.nodes){node.setAttribute('transform',transform);node.setAttribute('opacity',style.opacity);node.firstElementChild.setAttribute('d',node.getAttribute('data-mask')==='true'?MotionKit.path(q.m,q.x,true):d);node.firstElementChild.setAttribute('stroke-dasharray',style.draw>=1?'none':`${style.draw} 1`);node.firstElementChild.setAttribute('visibility',style.draw>0?'visible':'hidden');}}for(const node of item.roots)node.setAttribute('transform',`translate(12 12) scale(${item.scale}) translate(-12 -12)`);}
  function targetState(item){return item.button.disabled?0:item.pin??(item.clickUntil?2:(item.hover||(item.focus&&item.button.matches(':focus-visible'))?1:0));}
  function updateTarget(item,event){const state=targetState(item),changed=state!==item.state;if(state===0&&changed)item.turns=MotionKit.turnGoal(item.tracks,'leave',item.turns);else if(state===1&&item.state===0)item.turns=MotionKit.turnGoal(item.tracks,'hover',item.turns);item.state=state;
    if(event==='settle'||item.pin!==null||item.button.disabled||!allowed()){item.sequence=null;MotionKit.targets(item.tracks,state,item.turns);}
    else if(event||changed){item.sequence=MotionKit.play(item.tracks,event||(state===0?'leave':state===1?'hover':'click'),item.turns);if(state===2)item.clickUntil=performance.now()+item.sequence.duration*+speed.value;}
    item.scaleTarget=item.pressed&&!item.button.disabled ? .955 : 1;if(item.isDemo)item.button.closest('.theme').querySelectorAll('.pose-choice').forEach(b=>b.setAttribute('aria-pressed',String(item.pin===+b.dataset.pose)));}
  function retarget(item,event,synced=false){if(!synced)advanceActive(performance.now());updateTarget(item,event);if(!allowed()){MotionKit.settle(item.tracks);item.scale=item.scaleTarget;item.scaleV=0;paint(item);active.delete(item);return;}active.add(item);schedule();}
  function schedule(){if(!frame&&active.size&&!document.hidden){last=performance.now();frame=requestAnimationFrame(tick);}}
  function advanceActive(now,playback=+speed.value){if(document.hidden){last=now;return;}const dt=Math.max(0,(now-last)/1000);last=now;
    for(const item of active){let remaining=dt;if(item.clickUntil&&item.sequence){const before=Math.max(0,(item.sequence.duration-item.sequence.elapsed)*playback/1000);if(remaining>=before){MotionKit.advanceSequence(item.tracks,item.sequence,before,playback);remaining-=before;item.clickUntil=0;updateTarget(item,'settle');}else item.clickUntil=now+(before-remaining)*1000;}const moving=MotionKit.advanceSequence(item.tracks,item.sequence,remaining,playback);[item.scale,item.scaleV]=MotionKit.step(item.scale,item.scaleV,item.scaleTarget,20/playback,dt);paint(item);const pending=item.sequence&&item.sequence.cursor<item.sequence.events.length;if(!moving&&!pending&&!item.clickUntil&&Math.abs(item.scale-item.scaleTarget)<.0004&&Math.abs(item.scaleV)<.006){MotionKit.settle(item.tracks);item.scale=item.scaleTarget;item.scaleV=0;paint(item);active.delete(item);}}
  }
  function tick(now){frame=0;advanceActive(now);
    if(active.size)frame=requestAnimationFrame(tick);
  }
  function activate(item){if(item.button.disabled)return;advanceActive(performance.now());item.pin=null;
    // ponytail: coalesce repeated clicks while a turn is pending; no spin queue.
    item.turns=MotionKit.turnGoal(item.tracks,'click',item.turns);
    item.clickUntil=allowed()?performance.now()+680*+speed.value:0;
    if(!allowed())item.pin=2;
    retarget(item,'click',true);
    status.textContent=`${item.theme.name} · ${item.key} · ${allowed()?'choreographed part motion':'motion off; click pose shown'}.`;
  }
  function bind(item){const b=item.button,on=(type,fn)=>b.addEventListener(type,e=>{advanceActive(performance.now());fn(e);});
    on('pointerenter',e=>{if(e.pointerType!=='touch'){item.pin=null;item.hover=true;retarget(item);}});
    on('pointerleave',()=>{item.hover=false;retarget(item);});
    on('focus',()=>{item.pin=null;item.focus=true;retarget(item);});
    on('blur',()=>{item.focus=false;item.keyPressed=false;item.pressed=item.pointerPressed;retarget(item);});
    on('pointerdown',e=>{if(e.button===0&&!b.disabled){item.pin=null;item.pointerPressed=true;item.pressed=true;retarget(item);}});
    on('keydown',e=>{if(!['Enter',' '].includes(e.key))return;if(e.repeat){e.preventDefault();return;}item.pin=null;item.keyPressed=true;item.pressed=true;retarget(item);});
    on('keyup',e=>{if(!['Enter',' '].includes(e.key))return;item.keyPressed=false;item.pressed=item.pointerPressed;retarget(item);});
    on('click',()=>{if(b.disabled)return;if(!item.isDemo&&item.key==='bookmark'){setSaved(item,b.getAttribute('aria-pressed')!=='true');syncSaved();}activate(item);});
  }
  function create(button,theme,key,isDemo=false){const tracks=MotionKit.makeTracks(isDemo&&key==='bookmark'?theme.demo:theme.icons[key]);for(const [i,q]of tracks.entries())q.nodes=[...button.querySelectorAll(`[data-part="${i}"]`)];const item={button,theme,key,isDemo,tracks,roots:[...button.querySelectorAll('.motion-root')],hover:false,focus:false,pin:null,pressed:false,pointerPressed:false,keyPressed:false,turns:0,clickUntil:0,sequence:null,state:0,scale:1,scaleV:0,scaleTarget:1};items.push(item);bind(item);return item;}
  function inspect(item,key){if(key===item.key)return;active.delete(item);item.key=key;item.turns=item.clickUntil=0;item.sequence=null;item.pin=null;item.state=0;item.scale=item.scaleTarget=1;item.scaleV=0;item.pressed=item.pointerPressed=item.keyPressed=item.hover=item.focus=false;const bookmark=key==='bookmark',card=item.button.closest('.theme');item.button.querySelector('.stage').innerHTML=MotionKit.svg(item.theme,key,154,0,bookmark);item.button.setAttribute('aria-label',`${item.theme.name}: animate ${key}`);item.tracks=MotionKit.makeTracks(bookmark?item.theme.demo:item.theme.icons[key]);for(const [i,q]of item.tracks.entries())q.nodes=[...item.button.querySelectorAll(`[data-part="${i}"]`)];item.roots=[...item.button.querySelectorAll('.motion-root')];card.querySelector('.inspect').value=key;card.querySelector('.motion-strip').innerHTML=MotionKit.storyboard(item.theme,key,84,bookmark);card.querySelector('.reference-label').textContent=`LIVE · ${key.toUpperCase()}`;for(const b of card.querySelectorAll('.pose-choice')){const pose=+b.dataset.pose;b.innerHTML=MotionKit.svg(item.theme,key,88,pose,bookmark)+`<span>${['Rest','Hover','Click'][pose]}</span>`;b.setAttribute('aria-label',`Pin ${item.theme.name} ${key} ${['rest','hover','click'][pose]} pose`);b.setAttribute('aria-pressed','false');}card.querySelector('.part-count').textContent=`${item.tracks.length} ${key} parts · hover + click choreography`;}
  function setSaved(item,on){item.button.dataset.saved=String(on);item.button.setAttribute('aria-pressed',String(on));}
  function syncSaved(){const b=items.filter(i=>!i.isDemo&&i.key==='bookmark'),n=b.filter(i=>i.button.dataset.saved==='true').length;saved.checked=n===b.length;saved.indeterminate=n>0&&n<b.length;}
  for(const theme of motionThemes){const card=gallery.querySelector(`[data-theme="${theme.id}"]`);const group=[];for(const b of card.querySelectorAll('.sample'))group.push(create(b,theme,b.dataset.key));const demo=create(card.querySelector('.pose-live'),theme,'reload',true);group.push(demo);const choices=[...card.querySelectorAll('.pose-choice')];
    card.querySelector('.inspect').addEventListener('change',e=>inspect(demo,e.target.value));
    for(const item of group.filter(i=>!i.isDemo))item.button.addEventListener('click',()=>{if(item.button.disabled)return;inspect(demo,item.key);activate(demo);});
    for(const b of choices)b.addEventListener('click',()=>{advanceActive(performance.now());demo.pin=+b.dataset.pose;demo.clickUntil=0;if(demo.pin===2)demo.turns=MotionKit.turnGoal(demo.tracks,'click',demo.turns);retarget(demo);choices.forEach(c=>c.setAttribute('aria-pressed',String(c===b)));status.textContent=`${theme.name} · ${['rest','hover','click'][demo.pin]} pose pinned.`;});
    card.querySelector('.replay').addEventListener('click',()=>{group.forEach(i=>activate(i));status.textContent=`${theme.name} · 7 motion previews.`;});
  }
  document.addEventListener('pointerup',()=>{advanceActive(performance.now());for(const i of items)if(i.pointerPressed){i.pointerPressed=false;i.pressed=i.keyPressed;retarget(i);}});
  document.addEventListener('pointercancel',()=>{advanceActive(performance.now());for(const i of items)if(i.pointerPressed){i.pointerPressed=false;i.pressed=i.keyPressed;retarget(i);}});
  function stopAll(){if(frame)cancelAnimationFrame(frame);frame=0;active.clear();for(const i of items){i.clickUntil=0;i.sequence=null;i.pressed=i.pointerPressed=i.keyPressed=i.hover=i.focus=false;i.pin=null;i.turns=0;i.state=0;i.scale=i.scaleTarget=1;i.scaleV=0;MotionKit.targets(i.tracks,0);MotionKit.settle(i.tracks);paint(i);}gallery.querySelectorAll('.pose-choice').forEach(b=>b.setAttribute('aria-pressed','false'));}
  window.addEventListener('blur',()=>{advanceActive(performance.now());for(const i of items)if(active.has(i)||i.pressed||i.hover||i.focus){i.pressed=i.pointerPressed=i.keyPressed=i.hover=i.focus=false;retarget(i);}});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){pausedAt=performance.now();if(frame)cancelAnimationFrame(frame);frame=0;}else{const now=performance.now(),pause=pausedAt?now-pausedAt:0;for(const i of items)if(i.clickUntil)i.clickUntil+=pause;pausedAt=0;schedule();}});
  function updateMotion(){stopAll();document.documentElement.dataset.motion=allowed()?'on':'off';status.textContent=reduced.matches?'System reduced motion: state changes shown without animation.':allowed()?'Motion enabled. Hover, press, or click.':'Motion off: state changes shown without animation.';}
  motion.addEventListener('change',updateMotion);reduced.addEventListener('change',updateMotion);
  speed.addEventListener('change',()=>{const now=performance.now(),previous=+speed.dataset.previous||1;advanceActive(now,previous);for(const i of items)if(i.clickUntil)i.clickUntil=now+Math.max(0,i.clickUntil-now)*(+speed.value/previous);speed.dataset.previous=speed.value;status.textContent=`Playback ${speed.options[speed.selectedIndex].text}; current positions and velocities retained.`;});
  $('family').addEventListener('change',e=>{stopAll();for(const c of gallery.children)c.hidden=e.target.value!=='all'&&c.dataset.family!==e.target.value;status.textContent=`${gallery.querySelectorAll('.theme:not([hidden])').length} themes shown.`;});
  $('surface').addEventListener('change',e=>document.documentElement.dataset.surface=e.target.value);
  saved.addEventListener('change',()=>{items.filter(i=>!i.isDemo&&i.key==='bookmark').forEach(i=>setSaved(i,saved.checked));saved.indeterminate=false;});
  $('state').addEventListener('change',()=>{stopAll();const state=$('state').value;for(const i of items){const busy=state==='busy'&&!i.isDemo&&['reload','download'].includes(i.key);i.button.disabled=state==='disabled'||busy;i.button.setAttribute('aria-busy',String(busy));i.button.dataset.busy=String(busy);}gallery.querySelectorAll('.pose-choice,.replay,.inspect').forEach(b=>b.disabled=state==='disabled');status.textContent=state==='disabled'?'All controls disabled.':state==='busy'?`${motionThemes.length*2} reload/download controls paused.`:`${motionThemes.length*7} motion previews interactive.`;});
  document.documentElement.dataset.motion=allowed()?'on':'off';
  globalThis.iconflowConcepts={themes:motionThemes,items,active,activate,retarget,stopAll,allowed,check(){const counts=MotionKit.validate(motionThemes);if(items.length!==motionThemes.length*7)throw Error('Seven controllers per theme required');if(gallery.querySelectorAll('.pose-choice').length!==motionThemes.length*3)throw Error('Three pose controls per theme required');return {...counts,controllers:items.length,active:active.size};}};
})();
