#!/usr/bin/env python3
"""Draws Glassflow's animated Library button icons and writes them into
glassflow/userChrome.css, between the LIBRARY SPRITES markers.

Each icon is a strip of 36 frames of 18x18, the format of Zen's own
library-sprite.svg, so Zen's hover and unhover keyframes play it unchanged.
Frame 0 is the resting icon; frame 35 is held while the button is hovered.
Lines are 1.4px with sharp corners and square ends, in the toolbar's icon
colour (context-fill): minimal geometric shapes rather than objects.

python3 tools/library-sprites.py
"""
from math import cos, sin, radians
from pathlib import Path
from urllib.parse import quote

FRAMES, SIZE = 36, 18
CSS = Path(__file__).resolve().parent.parent / "glassflow" / "userChrome.css"
START, END = "/* LIBRARY SPRITES: generated by tools/library-sprites.py */", "/* END LIBRARY SPRITES */"


def ease_out_back(t, s=1.7):
    t -= 1
    return 1 + (s + 1) * t ** 3 + s * t ** 2


def ease_in_out(t):
    return 3 * t * t - 2 * t * t * t


def clamp(t):
    return max(0.0, min(1.0, t))


def span(t, a, b):
    """Progress through [a, b] of the whole animation."""
    return clamp((t - a) / (b - a))


def pts(points):
    return " ".join(f"{x:.2f} {y:.2f}" for x, y in points)


def poly(points, closed=True):
    return f"<path d='M{pts(points)}{'Z' if closed else ''}'/>"


def turn(points, deg, cx=9, cy=9):
    c, s = cos(radians(deg)), sin(radians(deg))
    return [(cx + (x - cx) * c - (y - cy) * s, cy + (x - cx) * s + (y - cy) * c) for x, y in points]


def layers(t):
    # Three stacked planes that pull apart, then settle a little open.
    gap = ease_out_back(span(t, 0, 1), 2.4) * 1.3
    top = [(2.5, 6.5 - gap), (9, 3 - gap), (15.5, 6.5 - gap), (9, 10 - gap)]
    mid = [(2.5, 10), (9, 13.5), (15.5, 10)]
    low = [(2.5, 13.5 + gap), (9, 17 + gap * 0.6), (15.5, 13.5 + gap)]
    low = [(x, min(y, 16.6)) for x, y in low]
    return poly(top) + poly(mid, False) + poly(low, False)


def hex_scan(t):
    # A hexagon with a scan line sweeping down and settling across its middle.
    hexagon = [(9 + 6.5 * cos(radians(a)), 9 + 6.5 * sin(radians(a))) for a in range(-90, 270, 60)]
    sweep = span(t, 0, 0.7)
    y = 9 + (-4.2 + ease_in_out(sweep) * 8.4) if t < 0.7 else 9 + 4.2 - ease_out_back(span(t, 0.7, 1)) * 4.2
    half = 6.5 * cos(radians(30)) - abs(y - 9) * 0.58 - 1.4
    return poly(hexagon) + f"<path d='M{9 - half:.2f} {y:.2f}H{9 + half:.2f}'/>"


def brackets(t):
    # Focus brackets snap in on a diamond that turns and grows.
    k = ease_out_back(span(t, 0, 0.8), 2) * 1.6
    a, b, L = 2.5 + k, 15.5 - k, 3.6
    corners = (f"<path d='M{a:.2f} {a + L:.2f}V{a:.2f}H{a + L:.2f}M{b - L:.2f} {a:.2f}H{b:.2f}V{a + L:.2f}"
               f"M{b:.2f} {b - L:.2f}V{b:.2f}H{b - L:.2f}M{a + L:.2f} {b:.2f}H{a:.2f}V{b - L:.2f}'/>")
    r = 1.6 + ease_out_back(span(t, 0.2, 1)) * 0.9
    return corners + poly(turn([(9, 9 - r), (9 + r, 9), (9, 9 + r), (9 - r, 9)], ease_out_back(span(t, 0.1, 1)) * 90))


def grid(t):
    # Four tiles; one lifts out of the grid and turns to a diamond.
    out = ease_out_back(span(t, 0, 0.9), 2)
    tile = lambda x, y: [(x, y), (x + 5, y), (x + 5, y + 5), (x, y + 5)]
    moved = turn(tile(10.5, 2.5), out * 45, 13, 5)
    moved = [(x + out * 1.2, y - out * 1.2) for x, y in moved]
    return poly(tile(2.5, 2.5)) + poly(tile(2.5, 10.5)) + poly(tile(10.5, 10.5)) + poly(moved)


def chevrons(t):
    # Chevrons fall into a baseline; the next one drops in behind them.
    shift = ease_in_out(span(t, 0, 1)) * 4
    out = []
    for i, y0 in enumerate((-1.5, 2.5, 6.5)):
        y = y0 + shift
        if -2 < y < 9.5:
            out.append(f"<path d='M4.5 {y:.2f}L9 {y + 4:.2f}L13.5 {y:.2f}' stroke-opacity='{min(1, (y + 2) / 3.5):.2f}'/>")
    return "".join(out) + "<path d='M3 15.5H15'/>"


def orbit(t):
    # A diamond core with an open orbit that swings round it.
    spin = ease_out_back(span(t, 0, 1), 1.4) * 200
    arc0, arc1 = radians(-60 + spin), radians(210 + spin)
    x0, y0, x1, y1 = 9 + 6.5 * cos(arc0), 9 + 6.5 * sin(arc0), 9 + 6.5 * cos(arc1), 9 + 6.5 * sin(arc1)
    core = turn([(9, 6.6), (11.4, 9), (9, 11.4), (6.6, 9)], ease_out_back(span(t, 0.15, 1)) * 45)
    return f"<path d='M{x0:.2f} {y0:.2f}A6.5 6.5 0 1 1 {x1:.2f} {y1:.2f}'/>" + poly(core)


def split(t):
    # A frame splits down the middle and slides open on a vertical core.
    d = ease_out_back(span(t, 0, 0.8), 2) * 1.8
    core = ease_out_back(span(t, 0.25, 1))
    left = poly([(8.25 - d, 3), (3 - d * 0.4, 3), (3 - d * 0.4, 15), (8.25 - d, 15)], False)
    right = poly([(9.75 + d, 3), (15 + d * 0.4, 3), (15 + d * 0.4, 15), (9.75 + d, 15)], False)
    mid = f"<path d='M9 {9 - core * 3.5:.2f}V{9 + core * 3.5:.2f}'/>" if core > 0.05 else ""
    return left + right + mid


def pulse(t):
    # A diamond whose inner diamond pushes out to the edge as a new one forms.
    dia = lambda r: [(9, 9 - r), (9 + r, 9), (9, 9 + r), (9 - r, 9)]
    grow = ease_in_out(span(t, 0, 0.75))
    inner = 3 + grow * 4
    fresh = ease_out_back(span(t, 0.5, 1)) * 3
    out = poly(dia(7.2))
    out += f"<path d='M{pts(dia(inner))}Z' stroke-opacity='{1 - grow * 0.85:.2f}'/>"
    if fresh > 0.1:
        out += poly(dia(fresh))
    return out


ICONS = {3: ("Layers", layers), 4: ("Hex scan", hex_scan), 5: ("Focus", brackets), 6: ("Grid", grid),
         7: ("Chevrons", chevrons), 8: ("Orbit", orbit), 9: ("Split", split), 10: ("Pulse", pulse)}


def sprite(draw):
    # Each frame is clipped to its own square, so nothing bleeds into its neighbour.
    frames = "".join(f"<g transform='translate({i * SIZE})'><g clip-path='url(#f)'>{draw(i / (FRAMES - 1))}</g></g>"
                     for i in range(FRAMES))
    frames = f"<clipPath id='f'><rect width='{SIZE}' height='{SIZE}'/></clipPath>" + frames
    svg = (f"<svg xmlns='http://www.w3.org/2000/svg' width='{FRAMES * SIZE}' height='{SIZE}' fill='none' "
           "stroke='context-fill' stroke-opacity='context-fill-opacity' stroke-width='1.4' "
           f"stroke-linecap='square' stroke-linejoin='miter'>{frames}</svg>")
    return "url(\"data:image/svg+xml," + quote(svg, safe="/:=' ,.-()") + "\")"


def main():
    rules = [START]
    for value, (name, draw) in ICONS.items():
        rules.append(f'/* {name} */\n@media (-moz-pref("zzglass.sidebar.library-style", {value})) {{\n'
                     f"  #zen-library-button .zen-library-sprite::before {{ background-image: {sprite(draw)} !important; }}\n}}")
    rules.append(END)
    css = CSS.read_text()
    block = "\n".join(rules)
    css = css[:css.index(START)] + block + css[css.index(END) + len(END):] if START in css else css.rstrip() + "\n\n" + block + "\n"
    CSS.write_text(css)
    print(f"wrote {len(ICONS)} sprites, {len(block) // 1024} KB")


if __name__ == "__main__":
    main()
